export const suppliers = [
  {
    emoji: "🛒",
    name: "AliExpress",
    url: "https://aliexpress.com",
    category: "General",
    shipping: "10–20 days",
    minOrder: "No minimum",
  },
  {
    emoji: "📦",
    name: "CJ Dropshipping",
    url: "https://cjdropshipping.com",
    category: "General",
    shipping: "7–15 days",
    minOrder: "No minimum",
  },
  {
    emoji: "⚡",
    name: "Zendrop",
    url: "https://zendrop.com",
    category: "General",
    shipping: "5–10 days",
    minOrder: "No minimum",
  },
  {
    emoji: "👗",
    name: "Spocket",
    url: "https://spocket.co",
    category: "Fashion/Beauty",
    shipping: "3–7 days",
    minOrder: "No minimum",
  },
  {
    emoji: "🏷️",
    name: "Temu Wholesale",
    url: "https://temu.com",
    category: "General",
    shipping: "7–14 days",
    minOrder: "No minimum",
  },
  {
    emoji: "🔌",
    name: "DHgate",
    url: "https://dhgate.com",
    category: "General/Electronics",
    shipping: "10–20 days",
    minOrder: "$1 minimum",
  },
];
